### ISSUE TITLE
Right Click Is Iffy

### ISSUE THREAD

**Issue by greenturtle537** [Tartarus6/temp_notes#19]
On Main: 939a65c4f02b8a14bb90d37726bcf5ad57033773, tested Windows 11 running Google Chrome 135.0.7049.96.

A trackpad can deliver two kinds of right clicks, hard rights and soft rights.

Hard rights open the normal right click web dialogue, while soft clicks open the one needed to create files.

**I like the right click functionality of temp_notes, but I have fat thumbs.**

Can we get rid of web dialogue right clicks? Maybe see https://superuser.com/questions/488811/how-to-disable-right-click-on-certain-websites

Thanks @Tartarus6

**Comment by Tartarus6** [comment]
I believe this is fixed in #13 . The problem was that the context menu content wasn't being updated when the node changed, so if you add a new folder and a node that used to be a note is now a folder, the stuff in the context menu wouldn't change.

fixed using $effect

**Comment by Tartarus6** [comment]
@greenturtle537 do tell me if it still happens, since i merged #13

**Comment by greenturtle537** [comment]
@Tartarus6 Still persists on https://github.com/Tartarus6/temp_notes/pull/13

![Image](https://github.com/user-attachments/assets/5e8dc366-e716-4d8c-920b-83cfa41fa173)

Added image of what we don't want

**Comment by Tartarus6** [comment]
the context menu is only implemented in the file explorer right now
